version: "3.9"
networks:
  bridge_network:
    driver: bridge
services:
  mysqldb:
    container_name: mysql_sstech_env_local
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=sstech
      - MYSQL_ROOT_PASSWORD=sstech246357
    ports:
      - "4727:3306"
    networks:
      - bridge_network
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
volumes:
  mysql_data:
# docker compose -p env_local_my_sstech -f docker-compose.env.local.yaml up -d
# docker exec -it mysql_sstech_env_local /bin/bash
# docker compose -p env_local_my_sstech down
# docker run -d -p 9000:9000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
# Portainer admin - lambada246357
