version: "3.9"
networks:
  bridge_network:
    driver: bridge
services:
  nginx:
    container_name: nginx_papaya_env_production
    build:
      context: ./stack-fe
      dockerfile: env.production.Dockerfile
    ports:
      - "3004:80"
    volumes:
      - ./nginx/config/default.env.production.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bridge_network
    restart: unless-stopped
  mysqldb:
    container_name: mysql_sstech_env_production
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=sstech
      - MYSQL_ROOT_PASSWORD=sstech246357
    ports:
      - "3306:3306"
    networks:
      - bridge_network
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
  backend:
    container_name: backend_papaya_env_production
    build:
      context: ./stack-be
      dockerfile: env.production.Dockerfile
    ports:
      - "8004:8000"
    networks:
      - bridge_network
    restart: unless-stopped
volumes:
  mongo_data:
# docker compose -p env_production_my_papaya -f docker-compose.env.production.yaml up -d
# docker compose -p env_production_my_papaya down
# docker run -d -p 9000:9000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
# Portainer admin - lambada246357
