version: "3.9"
networks:
  bridge_network:
    driver: bridge
services:
  nginx:
    container_name: nginx_papaya_env_test
    build:
      context: ./stack-fe
      dockerfile: env.test.Dockerfile
    ports:
      - "3002:80"
    volumes:
      - ./nginx/config/default.env.test.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bridge_network
    restart: unless-stopped
  mongo:
    container_name: mongo_papaya_env_test
    image: mongo:6.0
    environment:
      - MONGO_INITDB_DATABASE=papaya
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Godofwar246357
    expose:
      - "27017"
    networks:
      - bridge_network
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
  backend:
    container_name: backend_papaya_env_test
    build:
      context: ./stack-be
      dockerfile: env.test.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - bridge_network
    restart: unless-stopped
volumes:
  mongo_data:
# docker compose -p env_test_my_papaya -f docker-compose.env.test.yaml up -d
# docker compose -p env_test_my_papaya down
# Portainer admin - lambada246357
